// Generated by ReScript, PLEASE EDIT WITH CARE


function makeRequestInit(method, headers, body, redirect, param) {
  return {
          method: method,
          headers: headers,
          body: body,
          redirect: redirect
        };
}

function makeResponseInit(status, statusText, headers, param) {
  return {
          status: status,
          statusText: statusText,
          headers: headers
        };
}

export {
  makeRequestInit ,
  makeResponseInit ,
  
}
/* No side effect */
