// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Headers = {};

function makeInit(cf, method, headers, body, redirect, param) {
  return {
          cf: cf,
          method: method,
          headers: headers,
          body: body,
          redirect: redirect
        };
}

var $$Request = {
  makeInit: makeInit
};

function makeInit$1(status, statusText, headers, param) {
  return {
          status: status,
          statusText: statusText,
          headers: headers
        };
}

var $$Response = {
  makeInit: makeInit$1
};

export {
  $$Headers ,
  $$Request ,
  $$Response ,
  
}
/* No side effect */
