// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "./Http.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function handleRequest(_request) {
  return Promise.resolve(new Response("Hello world", Http.makeResponseInit(undefined, undefined, Js_dict.fromArray([[
                            "Content-Type",
                            "text/plain"
                          ]]), undefined)));
}

addEventListener("fetch", (function ($$event) {
        $$event.respondWith(handleRequest($$event.request));
        
      }));

export {
  handleRequest ,
  
}
/*  Not a pure module */
